bromley:
    name: 'Bromley Huckabee'
    birthyear: 1959
    sex: male

luke:
    name: 'Luke Bery'
    birthyear: 2008
    sex: 'male'
    start_year: 2020
    pet: ['Cotton', 'owl']

lissy:
    name: 'Lissy Spinster'
    birthyear: 2008
    sex: 'female'
    start_year: 2020
    pet: ['Ramses', 'cat']

